### ISSUE TITLE
lens

### ISSUE THREAD

**Issue by guaraqe** [nikita-volkov/rebase#5]
What do you think about lens? It certainly fits the package goals, but it is huge and complicated. An alternative would be to add something like lens-simple, which is enough for simple use, but I don't know about advanced usage.

**Comment by nikita-volkov** [comment]
Same as with streaming libraries, it's best to stay away from it, because it's subject to research and there's a high competition in that area. Also the "lens" library in particular is not just a library, but generally an alternative approach to programming in Haskell.

To quote the package's goals:

> The policy behind the package is only to reexport the non-ambiguous and non-controversial APIs, which the community has obviously settled on.
