### ISSUE TITLE
Partial list functions

### ISSUE THREAD

**Issue by afcady** [nikita-volkov/rebase#6]
What to do about these infamous scourges?  This looks nice to me:

https://hackage.haskell.org/package/listsafe-0.1.0.1

It exports safe versions of the partial list functions from `Data.List`, using the _same_ names, but different types -- signaling errors with `MonadThrow`.  This is really the best way to do it IMHO, instead of just using `Maybe` -- you  get back some of the convenience of the partial versions that way.

I guess you might argue that such a solution has no consensus behind it.  Another option would be simply not exporting the partial functions.  (The partial functions are themselves lacking consensus.)

**Comment by nikita-volkov** [comment]
I agree that something could be done about the partial functions. Maybe an alternative module to `Rebase.Data.List` could also be exported, with it gaining a priority in the reexports from `Rebase.Prelude`. However I'm strongly opposed to a solution involving `MonadThrow`, since exceptions are a quite notorious subject.

This needs a deeper analysis.

**Comment by afcady** [comment]
Hm, can you explain more why you are opposed to `MonadThrow`?  I find that very surprising.  Of course `Maybe` is an instance of `MonadThrow`, which is always available in a pure context, thus exceptions will not be involved unless requested by the caller.  So I really don't understand at all what you mean.

**Comment by nikita-volkov** [comment]
Whether exceptions get directly involved or not, I'd rather not make the API reliant on classes, which do involve them. I am one of many who find the sole concept of exceptions an ugly hack into the otherwise consistent type system of Haskell. Since I'm not alone, this makes it a controversial subject.

**Comment by guaraqe** [comment]
At the same time, rebase is exporting `MonadError`. If the problem is with `MonadThrow`, making an equivalent using this should be very easy. If you get to a consensus on what is appropriate, I volunteer to make it.

**Comment by nikita-volkov** [comment]
@guaraqe `MonadError` is parameterised by the type of error, which, I think makes it impossible to do the same using it.

Either way, you can try to implement it in a separate library. If you succeed, I then will introduce a dependency from "rebase" to it. You see, I'd rather let "rebase" be more of an aggregator kind of library, then implement things in it directly.

**Comment by nikita-volkov** [comment]
BTW, this can be easily implemented using the `Alternative` interface, where `Nothing` becomes `empty` and `Just` - `pure`.

Yes, `Alternative` is definitely the best way to go.

**Comment by guaraqe** [comment]
The `MonadThrow` version was also throwing a custom error type, the mimicking would be one-to-one, but I see the problem with the approach. Yes, implementing it separately is what I was talking about. 

I don't see exactly why `Alternative` is the best choice. The problems with partial list functions are not pattern-matching the empty list or using negative indexes, what is the advantage that `<|>` gives when dealing with these ? (as `empty` corresponds well with `Nothing` and gives no more information than that).

**Comment by guaraqe** [comment]
Or in the same line, why not `MonadPlus` instead, as the instances are similar?

**Comment by nikita-volkov** [comment]
I mean something like this:

``` haskell
head :: Alternative f => [a] -> f a
head =
  \case
    head : _ -> pure head
    _ -> empty
```

> I don't see exactly why `Alternative` is the best choice.

It's most general.

> what is the advantage that `<|>` gives

It's not as much about the available operations as it is about such functions being specialisable to produce a plethora of specific output types, including `Maybe`, `[]`, `Validation`, `Success`, `Vector`, `EitherT`, `ExceptT` and so on.

> `empty` corresponds well with `Nothing` and gives no more information than that

You can neither produce any more information in both `MonadError` or `MonadThrow`. Go on, try it and you'll answer your question yourself.

> Or in the same line, why not `MonadPlus` instead, as the instances are similar?

`MonadPlus` is an older exact replica of `Alternative`, which however requires the more restrictive `Monad` constraint. After `Monad` became a subclass of `Applicative` it no longer has purpose of existence and I'd expect it to become deprecated eventually.

**Comment by guaraqe** [comment]
Fair enough. It's a class I don't use often (only for parsers), so I had to look after its instances and I hadn't seen the `EitherT` and `ExceptT` ones, I'm convinced.

I will work on it and report back here.

**Comment by guaraqe** [comment]
Two more thing to make more precise:

Some partial functions in `Data.List` (like `maximum`) have been generalized to their `Foldable` versions, which go out of the scope of lists only, but are just as straightforward to make safe. Do I put them there too?

Also, indexing (!!) is unsafe but the problem seems larger that the solution for the others and the solution less adequate. I personally wouldn't think it is worth.

**Comment by nikita-volkov** [comment]
It's all up to you, as you'll be the author of the discussed package.

Either way, I must inform you that the library you're making will have to mature before being reexported from "rebase".

**Comment by guaraqe** [comment]
Ok, great! Of course, I wouldn't want anyone using it without being sure it's doing its job well. Thanks for the idea and I will report back when I have time.

**Comment by afcady** [comment]
> You can neither produce any more information in both MonadError or MonadThrow. Go on, try it and you'll answer your question yourself.

k...

```
{-# LANGUAGE NoImplicitPrelude #-}
{-# LANGUAGE ViewPatterns      #-}
module Main where

import           Data.List.Safe
import           Rebase.Prelude hiding ((!!))

ls = [1..10]

main = do
  putStrLn $ either sentence show $ ls !! (-1)
  putStrLn $ either sentence show $ ls !! 5
  putStrLn $ either sentence show $ ls !! 20

sentence (fromException -> Just EmptyListException)      = "50 lashes"
sentence (fromException -> Just NegativeIndexException)  = "death"
sentence _                                               = "commuted"
```

**Comment by afcady** [comment]
Well, anyway, can we just get the partial list functions out of `Rebase.Prelude` immediately?  Because having to add another import is reasonable enough for the sake of compromise, but having to use `hiding (...)` is an intolerable oppression.

**Comment by guaraqe** [comment]
First version: https://github.com/guaraqe/safe-alternative. Covers all the functions from the library above and some more using a similar style.

**Comment by nikita-volkov** [comment]
@guaraqe
Your library looks good. Why don't you release it on Hackage?

BTW, the "safe" naming tendency for such packages is not as precise as "total". I mean, what you do with this package is present **total** functions. So I suggest using that word in the title instead.

**Comment by nikita-volkov** [comment]
@afcady
You can easily combine the current `Rebase.Prelude`, with [the "safe" library](http://hackage.haskell.org/package/safe), which doesn't introduce conflicts with the existing functions.

**Comment by nikita-volkov** [comment]
Actually, guys, I think we better put this issue on hold due to there not being any critical problem, and there being no clear consensus on which package to use for the total functions and whether the partial functions shouldn't be at all exported. Because I'm afraid otherwise it would introduce a very opinionated choice to this library, which not everyone will be happy about, and which also will make the API much less predictable. 

The reason for this is that I want to stay true to [a clear policy](http://hackage.haskell.org/package/rebase) in this package, so that it will be more stable, predictable and maintainable. The package already has multiple purposes, and I would rather be just doing my best at solving them.

---

However there are solutions, which might suit all. If you guys are looking for a more opinionated Prelude, you can easily do such one yourselves by simply depending on "rebase" and providing a Prelude, which is modified according to your needs. Thus you'll get "rebase" solving most of the package aggregation and dependency maintenance problems and a Prelude which suits your specific needs. Actually, in most of my projects I simply have a project-specific Prelude, which I actually recommend to have too.

**Comment by guaraqe** [comment]
Ok, no problem. Thanks for the suggestion on the name!
